/**
 * Fastify集成类型定义
 *
 * @description 直接使用Fastify官方类型定义，避免重复定义
 * @since 1.0.0
 */

// 重新导出Fastify官方类型
export type {
	FastifyInstance,
	FastifyRequest,
	FastifyReply,
	FastifyPluginOptions,
	FastifyListenOptions,
	FastifyBaseLogger,
	FastifyLoggerInstance,
	FastifySchema,
	FastifySchemaCompiler,
	FastifySerializerCompiler,
	RouteHandler,
	RouteHandlerMethod,
	RouteOptions,
	HookHandlerDoneFunction,
	preHandlerHookHandler,
	onRequestHookHandler,
	onResponseHookHandler,
	onSendHookHandler,
	onErrorHookHandler,
	onCloseHookHandler,
	onReadyHookHandler,
	onListenHookHandler,
	onRegisterHookHandler,
	onRouteHookHandler,
	preCloseHookHandler,
	preParsingHookHandler,
	preValidationHookHandler,
	preSerializationHookHandler,
	onRequestAbortHookHandler,
	onTimeoutHookHandler,
	preHandlerAsyncHookHandler,
	onRequestAsyncHookHandler,
	onResponseAsyncHookHandler,
	onSendAsyncHookHandler,
	onErrorAsyncHookHandler,
	onCloseAsyncHookHandler,
	onReadyAsyncHookHandler,
	onListenAsyncHookHandler,
	preCloseAsyncHookHandler,
	preParsingAsyncHookHandler,
	preValidationAsyncHookHandler,
	preSerializationAsyncHookHandler,
	onRequestAbortAsyncHookHandler,
	onTimeoutAsyncHookHandler,
	RequestGenericInterface,
	RouteGenericInterface,
	FastifyPlugin,
	FastifyPluginAsync,
	FastifyPluginCallback,
	FastifyRegister,
	FastifyRegisterOptions,
	RegisterOptions,
	FastifyTypeProvider,
	FastifyTypeProviderDefault,
	LogLevel,
	FastifyLoggerOptions,
	PrintRoutesOptions,
	FastifyServerFactory,
	FastifyServerFactoryHandler,
	FastifyContextConfig,
	FastifyReplyContext,
	FastifyRequestContext,
	FastifySchemaValidationError,
	HTTPMethods,
	RawServerBase,
	RawServerDefault,
	RawRequestDefaultExpression,
	RawReplyDefaultExpression,
	RequestBodyDefault,
	RequestHeadersDefault,
	RequestParamsDefault,
	RequestQuerystringDefault,
	ContextConfigDefault,
	SafePromiseLike,
	RequestPayload,
	DoneFuncWithErrOrRes,
	FastifyHttp2SecureOptions,
	FastifyHttp2Options,
	FastifyHttpsOptions,
	FastifyHttpOptions,
	FastifyServerOptions,
	FastifyErrorCodes,
	FastifyBodyParser,
	FastifyContentTypeParser,
	AddContentTypeParser,
	ConstructorAction,
	ProtoAction,
	RouteShorthandMethod,
	RouteShorthandOptions,
	RouteShorthandOptionsWithHandler
} from 'fastify';

// 重新导出Fastify实例创建函数
export { fastify, default } from 'fastify';
